### ISSUE TITLE
I have encountered the following problems with other browsers

### ISSUE THREAD

**Issue by aaaasssdd** [tinode/example-react-js#11]
I have encountered the following problems with other browsers. Are there any suggestions to solve this problem? Thank you。

VM148:1 You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/
console.warn @ VM148:1
u @ babel.min.js:24
f @ babel.min.js:1
(anonymous) @ babel.min.js:1

**Comment by or-else** [comment]
Yes, the code is not precompiled with Babel but transformed in the browser. You are welcome to send a pull request.

**Comment by or-else** [comment]
Any update on this?
