### ISSUE TITLE
[Unable to Delete Topic]

### ISSUE THREAD

**Issue by riandyrn** [tinode/example-react-js#2]
Hello,

I found issue when trying to delete inactive topic from my topic list. The issue is I cannot delete it, I must first activate the topic (by selecting it) then delete it. I also tried in online example just earlier and I found the same issue.

You could reproduce this issue by using following procedure:
1. login
2. don’t select any topic
3. try to delete any topic

or by using following procedure:
1. login
2. select any topic
3. try to delete another topic which hasn’t been selected before

I don’t know if this is server issue or just front-end issue. But since I found it in example app, so I just put it here.

Thanks

**Comment by or-else** [comment]
Confirmed

**Comment by or-else** [comment]
fixed in devel

**Comment by riandyrn** [comment]
Thanks (y)

**Comment by ChenZhaobin** [comment]
@or-else  I met the same problem,what  did you do to  solve this problem?

**Comment by or-else** [comment]
I cannot reproduce. Please file a new issue with details.
