### ISSUE TITLE
[Unable to Resubscribe P2P Topic]

### ISSUE THREAD

**Issue by riandyrn** [tinode/example-react-js#3]
Hello,

I found an issue regarding resubscribing P2P topic. The issue is I cannot resubscribe the p2p topic which I have previously deleted.

You could reproduce this issue by following these steps:
1. login
2. delete existing p2p topic
3. re-find the p2p topic which previously deleted by using “fnd” topic
4. try to subscribe that topic, it will throw Error 500

I just recently try this on both local & online example, both of them have the same issue.

Thanks

**Comment by or-else** [comment]
Confirmed. Thanks!

**Comment by or-else** [comment]
Fixed in devel

**Comment by riandyrn** [comment]
Wow, that's fast :D
Thanks!
