### ISSUE TITLE
Show last message  in contact-comment

### ISSUE THREAD

**Issue by ChenZhaobin** [tinode/example-react-js#9]
Which is the best way to retrieve contact list with the last message in it ,and then I can show it in the contact-comment blcok which now shows the private field now.

**Comment by ChenZhaobin** [comment]
The way I can think of is to update key-value such as 'lastmessage:blabla" in public field  once someone post a message in the topic.This  works fine,does there any better way?

**Comment by or-else** [comment]
Don't store anything in `public` that you don't want everyone to see. `public` is really public. If you write last message to `public` everyone will see it.

Store it in `private`. Private is indeed private and it's unique per user-topic.

Private is an object, you can add a field to it.
